// <auto-generated />
using AutoMatics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automatics.Migrations
{
    [DbContext(typeof(AutoMaticsDbContext))]
    [Migration("20260629150622_ArquitecturaCompleta")]
    partial class ArquitecturaCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoMatics.Domain.Clientes.Model.Aggregates.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCrediticio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IngresosNetosMensuales")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AutoMatics.Domain.Clientes.Model.Aggregates.SustentoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumentoSustento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("SustentosClientes");
                });

            modelBuilder.Entity("AutoMatics.Domain.Creditos.Model.Aggregates.Credito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IndicadorTCEA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IndicadorTIR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IndicadorVAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MontoPrestamo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("int");

                    b.Property<string>("TipoTasa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTasa")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("AutoMatics.Domain.Creditos.Model.Aggregates.CronogramaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amortizacion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CreditoId")
                        .HasColumnType("int");

                    b.Property<decimal>("CuotaTotalMensual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NumeroMes")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SegurosYGastos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoPeriodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreditoId");

                    b.ToTable("CronogramaPagos");
                });

            modelBuilder.Entity("AutoMatics.Domain.IAM.Model.Aggregates.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AutoMatics.Domain.Clientes.Model.Aggregates.SustentoCliente", b =>
                {
                    b.HasOne("AutoMatics.Domain.Clientes.Model.Aggregates.Cliente", null)
                        .WithMany("Sustentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMatics.Domain.Creditos.Model.Aggregates.Credito", b =>
                {
                    b.OwnsOne("AutoMatics.Domain.Creditos.Model.ValueObjects.EvaluacionRiesgo", "EvaluacionRiesgo", b1 =>
                        {
                            b1.Property<int>("CreditoId")
                                .HasColumnType("int");

                            b1.Property<string>("Clasificacion")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("DecisionAutomatica")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<double>("ScoreRiesgo")
                                .HasColumnType("double");

                            b1.HasKey("CreditoId");

                            b1.ToTable("Creditos");

                            b1.WithOwner()
                                .HasForeignKey("CreditoId");
                        });

                    b.Navigation("EvaluacionRiesgo")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMatics.Domain.Creditos.Model.Aggregates.CronogramaPago", b =>
                {
                    b.HasOne("AutoMatics.Domain.Creditos.Model.Aggregates.Credito", null)
                        .WithMany("CronogramaPagos")
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMatics.Domain.Clientes.Model.Aggregates.Cliente", b =>
                {
                    b.Navigation("Sustentos");
                });

            modelBuilder.Entity("AutoMatics.Domain.Creditos.Model.Aggregates.Credito", b =>
                {
                    b.Navigation("CronogramaPagos");
                });
#pragma warning restore 612, 618
        }
    }
}
